MACRO(GROUP_FILE_TREE FILES)
    FOREACH(ITEM IN ITEMS ${FILES})
        GET_FILENAME_COMPONENT(SRC_PATH "${ITEM}" PATH)
        STRING(REPLACE "${CMAKE_SOURCE_DIR}/src" "" GROUP_PATH "${SRC_PATH}")
        STRING(REPLACE "/" "\\" GROUP_PATH "${GROUP_PATH}")
        SOURCE_GROUP("${GROUP_PATH}" FILES ${ITEM})
    ENDFOREACH()
ENDMACRO() # legacy, remove

MACRO(GROUP_FILE_TREE_FILTER_TARGET_NAME FILES TARGET_NAME)
    FOREACH(ITEM IN ITEMS ${FILES})
        GET_FILENAME_COMPONENT(SRC_PATH "${ITEM}" PATH)
        STRING(REPLACE "${CMAKE_SOURCE_DIR}/src/${TARGET_NAME}" "" GROUP_PATH "${SRC_PATH}")
        STRING(REPLACE "/" "\\" GROUP_PATH "${GROUP_PATH}")
        SOURCE_GROUP("${GROUP_PATH}" FILES ${ITEM})
    ENDFOREACH()
ENDMACRO()

MACRO(MAKE_LWGE_STATIC_LIB TARGET_NAME)
    FILE(GLOB_RECURSE "${TARGET_NAME}_SOURCES"
        "${CMAKE_CURRENT_SOURCE_DIR}/Public/*.cpp" "${CMAKE_CURRENT_SOURCE_DIR}/Public/*.hpp"
        "${CMAKE_CURRENT_SOURCE_DIR}/Private/*.cpp" "${CMAKE_CURRENT_SOURCE_DIR}/Private/*.hpp")
    ADD_LIBRARY(${TARGET_NAME} ${${TARGET_NAME}_SOURCES})
    GROUP_FILE_TREE_FILTER_TARGET_NAME("${${TARGET_NAME}_SOURCES}" ${TARGET_NAME})
    TARGET_INCLUDE_DIRECTORIES(${TARGET_NAME} PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}/Private)
    TARGET_INCLUDE_DIRECTORIES(${TARGET_NAME} PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/Public)
    SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES CXX_STANDARD 23)
    IF(MSVC)
        TARGET_COMPILE_OPTIONS(${TARGET_NAME} PRIVATE
            "/wd26812" # The enum type 'type-name' is unscoped. Prefer 'enum class' over 'enum'
            "/WX" "/W4" "/MP"
            )
    ENDIF()
ENDMACRO()

MACRO(MAKE_LWGE_INTERFACE TARGET_NAME)
    FILE(GLOB_RECURSE "${TARGET_NAME}_SOURCES"
        "${CMAKE_CURRENT_SOURCE_DIR}/Public/*.hpp")
    ADD_LIBRARY(${TARGET_NAME} INTERFACE ${${TARGET_NAME}_SOURCES})
    GROUP_FILE_TREE_FILTER_TARGET_NAME("${${TARGET_NAME}_SOURCES}" ${TARGET_NAME})
    TARGET_INCLUDE_DIRECTORIES(${TARGET_NAME} INTERFACE
        ${CMAKE_CURRENT_SOURCE_DIR}/Public)
ENDMACRO()
